### ISSUE TITLE
Incomplete reads from citybik.es

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/pan-bikes#2]
```bash
GET failed: IncompleteRead: IncompleteRead(48917 bytes read, 152295 more expected)
Traceback (most recent call last):
  File "/home/osmo/Source/pan-bikes/pan/util.py", line 50, in inner_wrapper
    return function(*args, **kwargs)
  File "/home/osmo/Source/pan-bikes/pan/provider.py", line 108, in list_networks
    networks = self._provider.list_networks()
  File "/home/osmo/Source/pan-bikes/providers/citybikes.py", line 30, in list_networks
    networks = pan.http.get_json(url)
  File "/home/osmo/Source/pan-bikes/pan/http.py", line 152, in get_json
    headers=headers)
  File "/home/osmo/Source/pan-bikes/pan/http.py", line 238, in _request_json
    text = _request(method, url, body, encoding, retry, headers)
  File "/home/osmo/Source/pan-bikes/pan/http.py", line 202, in _request
    blob = response.read()
  File "/usr/lib/python3.6/http/client.py", line 462, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.6/http/client.py", line 614, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(48917 bytes read, 152295 more expected)
```

This likely basically breaks the app for most users.

**Comment by otsaloma** [comment]
Fixed now, maybe.
